import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ShieldCheck } from 'lucide-react';

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="flex-center" style={{minHeight: '100vh', padding: '20px', background: 'var(--bg-color)'}}>
      <div className="surface fade-in" style={{width: '100%', maxWidth: '800px', padding: '30px', maxHeight: '90vh', overflowY: 'auto'}}>
        <div style={{display: 'flex', alignItems: 'center', marginBottom: '24px'}}>
          <button onClick={() => navigate(-1)} style={{background: 'none', border: 'none', cursor: 'pointer', padding: '8px', display: 'flex', alignItems: 'center', color: 'var(--text-color)'}} className="hover-lift">
            <ArrowLeft size={24} />
          </button>
          <h2 style={{margin: '0 0 0 16px', display: 'flex', alignItems: 'center', gap: '8px'}}>
            <ShieldCheck color="var(--primary-color)" /> Terms & Conditions
          </h2>
        </div>

        <div style={{lineHeight: '1.6', color: 'var(--text-color)'}}>
          <p style={{color: 'var(--text-muted)'}}>Last updated: June 2026</p>
          
          <h3 style={{marginTop: '24px'}}>1. Introduction</h3>
          <p>Welcome to Pocket Vyapaar. By accessing or using our application, you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree to these terms, please do not use our application.</p>

          <h3 style={{marginTop: '24px'}}>2. User Accounts</h3>
          <p>To use certain features of Pocket Vyapaar (as a Shop Owner or Customer), you must register for an account. You agree to provide accurate information and keep your account credentials secure. You are responsible for all activities that occur under your account.</p>

          <h3 style={{marginTop: '24px'}}>3. Digital Khata & Transactions</h3>
          <p>Pocket Vyapaar provides a digital ledger (Khata) to record transactions between shop owners and customers. While we strive for 100% accuracy, Pocket Vyapaar is not responsible for any disputes over recorded amounts, missing entries, or payment collections. Users are encouraged to verify all entries in real-time.</p>

          <h3 style={{marginTop: '24px'}}>4. Data Privacy & Security</h3>
          <p>We implement industry-standard security measures to protect your OTPs, passwords, and ledger data. Your financial records are strictly confidential and will not be shared with third parties without your explicit consent, except as required by law.</p>

          <h3 style={{marginTop: '24px'}}>5. Communication & Notifications</h3>
          <p>By registering, you consent to receive SMS, WhatsApp, and Email notifications regarding OTPs, transaction updates, and payment reminders generated by your connected shop owners.</p>

          <h3 style={{marginTop: '24px'}}>6. Limitation of Liability</h3>
          <p>Pocket Vyapaar and its developers ("innovative bros") shall not be liable for any indirect, incidental, special, or consequential damages resulting from the use or inability to use the service.</p>

          <h3 style={{marginTop: '24px'}}>7. Changes to Terms</h3>
          <p>We reserve the right to modify these terms at any time. We will notify users of any significant changes. Continued use of the app after such modifications constitutes your acknowledgment and agreement.</p>
          
          <div style={{marginTop: '40px', padding: '20px', background: 'var(--bg-muted)', borderRadius: '8px', textAlign: 'center'}}>
            <p style={{margin: 0, fontWeight: 'bold'}}>Pocket Vyapaar - Syncing Every Daily Deal</p>
            <p style={{margin: '8px 0 0 0', fontSize: '14px', color: 'var(--text-muted)'}}>Developed by innovative bros</p>
          </div>
        </div>
      </div>
    </div>
  );
}
